/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ThriftInterface
{
  public enum ArchiveStatus
  {
    Completed = 0,
    InProgress = 1,
    Paused = 2,
    Stopped = 3,
    Failed = 4,
    Local = 5,
  }
}
