/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftInterface
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Archive : TBase
  {
    private string _LocalID;
    private ArchiveStatus _Status;
    private ArchiveInfo _Info;
    private bool _Sandbox;

    public string LocalID
    {
      get
      {
        return _LocalID;
      }
      set
      {
        __isset.LocalID = true;
        this._LocalID = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="ArchiveStatus"/>
    /// </summary>
    public ArchiveStatus Status
    {
      get
      {
        return _Status;
      }
      set
      {
        __isset.Status = true;
        this._Status = value;
      }
    }

    public ArchiveInfo Info
    {
      get
      {
        return _Info;
      }
      set
      {
        __isset.Info = true;
        this._Info = value;
      }
    }

    public bool Sandbox
    {
      get
      {
        return _Sandbox;
      }
      set
      {
        __isset.Sandbox = true;
        this._Sandbox = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool LocalID;
      public bool Status;
      public bool Info;
      public bool Sandbox;
    }

    public Archive() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              LocalID = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Status = (ArchiveStatus)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              Info = new ArchiveInfo();
              Info.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Bool) {
              Sandbox = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Archive");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (LocalID != null && __isset.LocalID) {
        field.Name = "LocalID";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(LocalID);
        oprot.WriteFieldEnd();
      }
      if (__isset.Status) {
        field.Name = "Status";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Status);
        oprot.WriteFieldEnd();
      }
      if (Info != null && __isset.Info) {
        field.Name = "Info";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        Info.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.Sandbox) {
        field.Name = "Sandbox";
        field.Type = TType.Bool;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Sandbox);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Archive(");
      sb.Append("LocalID: ");
      sb.Append(LocalID);
      sb.Append(",Status: ");
      sb.Append(Status);
      sb.Append(",Info: ");
      sb.Append(Info== null ? "<null>" : Info.ToString());
      sb.Append(",Sandbox: ");
      sb.Append(Sandbox);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
