/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ThriftInterface
{
  public enum CertExportFormat
  {
    HTML = 0,
    YAML = 1,
    PDF = 2,
  }
}
