/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ThriftInterface
{
  public enum ErrorType
  {
    NoError = 0,
    Server = 1,
    Network = 2,
    Authentication = 3,
    Validation = 4,
    Other = 5,
    NotImplemented = 6,
    FileNotFound = 7,
  }
}
